
---
title: "Tutorial 1 – Data Science with R"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
---


# What is R?

R is software very useful for data manipulation, graphing, and statistics.   Table 1 compares it to other software.  Of note,  R uses a command language, like SQL, and because of this, it is a much better tool for principled data analysis. 

Table 1 - Comparison of R, SQL, Excel and Access for data manipulation


| Feature                            | R         | SQL    | Excel | Access |
| ---                                | ---       | ---    | ---   |---     |
| Graphing                           | Yes       | No     | Yes   | No     |
| Data filtering capabilities        | Excellent | Good   | Some  | Some   |
| Statistics functionality           | Extensive | Little | Some  | No     |
| Useful for very large datasets     | Yes       | Yes    | No    | Ok     |
| Uses English language commands     | Yes       | Yes    | No    | No     |
| Has Graphical User Interface (GUI) | No        | No     | Yes   | Yes    |
| Can use it via the web             | Yes       | Yes    | Yes   | No     |

# Using R

The easiest way to use R is through Rstudio, an environment that aids access to R’s features.  There are 2 ways to get to Rstudio:  

 1) via the web (like SQL), or
 1) installed on your own computer.  If you want to do this, the instructions for installing it on your own computer are on LMS.

These instructions will assume you are accessing the web Rstudio version.

# Rstudio on the web

Go to: https://him-rstudio.latrobe.edu.au/

Login using the chunk of your email address that is before '@students.latrobe.edu.au' (normally your student number), and your email password.   You will end up at the following screen.  Like in SQL, this is your own personal workspace, but with more features.  For example, you can edit and run R program files, view R help, and connect to databases.

The left side of the screen holds the command window, and also, any files you are currently editing. The top right quadrant  mainly lists your data, while the bottom right displays help text, graphics, and files in your directory.


Whenever I mention R henceforth, I assume that you are accessing R through Rstudio.

## Exercises
1) Where is the command window?
1) Where is the plot tab?

# Introduction to the Tidyverse

R itself has substantial functionality, but this functionality is greatly supplemented through the use of packages.  The tidyverse is a massive collection of 25 packages which make R much easier to use.

When you start R for the first time, it has no packages loaded.  To use a package, you use the library command, for example, 

library( tidyverse )

If the package you want to use is not yet loaded, the library command will give you an error, for example.  

Error in library(tidyverse) : there is no package called ‘tidyverse’


To get past this, you will need to install the package, using the install.packages command, for example (you do  not need to do this at https://him-rstudio.latrobe.edu.au/ , it is already done)

Install.packages('tidyverse ')

Now, go to https://r4ds.had.co.nz/data-visualisation.html, and answer the questions in sections 3.1 – 3.6. This will help you with the final exam.

